### PR TITLE
WIP: Upgrade dependencies, allow Symfony 4

### LINKED ISSUE #2: Are there any plans to make a Symfony 4 bundle?
Are there any plans to make a Symfony 4 bundle?

Thanks

### PR DESCRIPTION
**Pull request by mhujer**
Closes #2

### CODE REVIEW

**Comment by mhujer** [comment]
@din-gi can you please test this branch, which supports Symfony 4?

It should be specified like this in `composer.json`:
`"mhujer/jms-serializer-uuid-bundle": "dev-mh-upgrade"`

**Comment by dinbrca** [comment]
@mhujer 

I have installed the package but for some reason it tells me: `Class uuid does not exist`

this is after adding the following to `services.yml` in the services section:
```
    mhujer.jms_serializer.uuid.uuid_serializer_handler:
        class: Mhujer\JmsSerializer\Uuid\UuidSerializerHandler
        tags:
            - { name: jms_serializer.subscribing_handler }
```

And the following to `bundles.php`:
```
Mhujer\JmsSerializer\Uuid\SymfonyBundle\MhujerJmsSerializerUuidBundle::class => ['all' => true],
```

Have any idea why?

Thanks for the help :)

**Comment by mhujer** [comment]
Adding a serivce manually should not be necessary - that's what the bundle is doing. Only registering the bundle in `bundles.php` as you did, should be enough.

Have you cleaned-up the cache? (just in case :-) )


I tested it yesterday. I had a testing class:

```php
<?php declare(strict_types = 1);

namespace App;

use JMS\Serializer\Annotation as JMS;

class User
{
	/**
	 * @JMS\Type("uuid")
	 * @var \Ramsey\Uuid\UuidInterface
	 */
	public $id;
}
```

And a DemoController:

```php
<?php

namespace App\Controller;

use App\User;
use JMS\Serializer\SerializerInterface;
use Ramsey\Uuid\Uuid;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Annotation\Route;

class DemoController extends Controller
{

	/** @var \JMS\Serializer\SerializerInterface */
	private $serializer;

	/**
	 */
	public function __construct(
		SerializerInterface $serializer
	)
	{
		$this->serializer = $serializer;
	}

	/**
	 * @Route("/")
	 * @return \Symfony\Component\HttpFoundation\Response
	 */
	public function demoAction()
	{
		$user = new User();
		$user->id = Uuid::uuid4();

		return new JsonResponse(
			$this->serializer->serialize($user, 'json')
		);
	}
}
```

**Comment by dinbrca** [comment]
Hey.. so I got some time today to check everything..
And I have to say I am sorry..
I tried doing your example and everything was ok.. I then knew that it must be something wrong with my project and I must be an idiot or something..

So turns out I was using the wrong serializer (I had couple of instances) and that my used instance didn't have the UUID extension registered..

Again - sorry..

Everything seems to be working well - if you can approve the pull so that it will stick to the master that will be amazing :) 

Thanks a bunch!

**Comment by mhujer** [comment]
@dinbrca merged and released as `3.0.0`, thanks for testing it! 👍

**Pull request merged**
